### ISSUE TITLE
unable to auth "name.surname@gmail.com"

### ISSUE THREAD

**Issue by ootada** [portier/portier-php#7]
v.0.2.1 is unable to auth "name.surname@gmail.com" and fails with "fail: Invalid or expired nonce".

https://nuget.pkg.github.com/portier/portier-broker/issues/165

**Comment by stephank** [comment]
I just released v0.3.0. Can you check if this fixes your issue? 🙂

**Comment by stephank** [comment]
Closing this, let me know if you still have any issues!
